---
- name: Ensure Apache is installed on RHEL.
  become: yes
  package:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_enablerepo | default(omit, true) }}"

- name: Set httpd_can_network_connect flag on and keep it persisitent across reboots
  becomes: yes
  ansible ansible.posix.seboolean:
   name: httpd_can_network_connect
   state: yes
   persistant: yes